<a href="https://colab.research.google.com/github/mmartin46/Data_Science_Research/blob/main/SavingMoney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [158]:
# Mark 16:16

In [197]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Mitchell_Martin_Budget_2024_ML.csv')

In [198]:
def get_filtered_dataset(df):
  df.dropna(axis='columns', inplace=True)
  # Drop the first row
  df = df.drop(df.index[0])

  # Convert date to a date format
  df['Date'] = pd.to_datetime(df['Date'])
  df['Remainder'] = 0
  remove_dollar_signs(df)
  return df

# Makes the columns numerical
def remove_dollar_signs(df):
  numeric_cols = list(df.columns)[3:-1]
  for col in numeric_cols:
    df[col] = pd.to_numeric(df[col].str.replace('[\$,]', '', regex=True), errors='coerce')


df = get_filtered_dataset(df)
df

,Date,Description,Category,Income,Subtract,Balance,Student Debt,Emergency Savings,Remainder
1,2024-03-01,Got Payed,Income,2000,0,2000,8250,0,0
2,2024-03-01,Church Giving,Church,0,200,1800,8250,0,0
3,2024-03-01,Student Loan Payment,Debt,0,600,1200,7650,0,0
4,2024-03-01,Daily Driving,Driving,0,400,800,7650,0,0
5,2024-03-01,Phone Bill,Phone,0,120,680,7650,0,0
...,...,...,...,...,...,...,...,...,...
136,2024-09-12,Emergency,Saving,0,360,2010,0,5300,0
137,2024-09-12,Invest,Saving,0,20,1990,0,5320,0
138,2024-09-12,Groceries,Groceries,0,40,1950,0,5320,0
139,2024-09-12,Eating Out,Entertainment,0,80,1870,0,5320,0
140,2024-09-12,Gym Membership,Entertainment,0,50,1820,0,5320,0

In [199]:
df.head(31)

,Date,Description,Category,Income,Subtract,Balance,Student Debt,Emergency Savings,Remainder
1,2024-03-01,Got Payed,Income,2000,0,2000,8250,0,0
2,2024-03-01,Church Giving,Church,0,200,1800,8250,0,0
3,2024-03-01,Student Loan Payment,Debt,0,600,1200,7650,0,0
4,2024-03-01,Daily Driving,Driving,0,400,800,7650,0,0
5,2024-03-01,Phone Bill,Phone,0,120,680,7650,0,0
6,2024-03-01,Emergency,Saving,0,360,320,7650,360,0
7,2024-03-01,Invest,Saving,0,20,300,7650,380,0
8,2024-03-01,Groceries,Groceries,0,40,260,7650,380,0
9,2024-03-01,Eating Out,Entertainment,0,80,180,7650,380,0
10,2024-03-01,Gym Membership,Entertainment,0,50,130,7650,380,0
11,2024-03-16,Got Payed,Income,2000,0,2130,7650,380,0
12,2024-03-16,Church Giving,Church,0,200,1930,7650,380,0
13,2024-03-16,Student Loan Payment,Debt,0,600,1330,7050,380,0
14,2024-03-16,Daily Driving,Driving,0,400,930,7050,380,0
15,2024-03-16,Phone Bill,Phone,0,120,810,7050,380,0
16,2024-03-16,Emergency,Saving,0,360,450,7050,740,0
17,2024-03-16,Invest,Saving,0,20,430,7050,760,0
18,2024-03-16,Groceries,Groceries,0,40,390,7050,760,0
19,2024-03-16,Eating Out,Entertainment,0,80,310,7050,760,0
20,2024-03-16,Gym Membership,Entertainment,0,50,260,7050,760,0
21,2024-03-31,Got Payed,Income,2000,0,2260,7050,760,0
22,2024-03-31,Church Giving,Church,0,200,2060,7050,760,0
23,2024-03-31,Student Loan Payment,Debt,0,600,1460,6450,760,0
24,2024-03-31,Daily Driving,Driving,0,400,1060,6450,760,0
25,2024-03-31,Phone Bill,Phone,0,120,940,6450,760,0
26,2024-03-31,Emergency,Saving,0,360,580,6450,1120,0
27,2024-03-31,Invest,Saving,0,20,560,6450,1140,0
28,2024-03-31,Groceries,Groceries,0,40,520,6450,1140,0
29,2024-03-31,Eating Out,Entertainment,0,80,440,6450,1140,0
30,2024-03-31,Gym Membership,Entertainment,0,50,390,6450,1140,0
31,2024-04-15,Got Payed,Income,2000,0,2390,6450,1140,0

In [200]:
paid_rows = df['Description'] == 'Got Payed'

In [201]:
df.loc[paid_rows, 'Remainder'] = (df['Balance'] - df['Income']) + df['Remainder'].shift()

In [202]:
df.head(30)

def fill_for_remainder_rows(df, cols, PR_INDEX, PR_VALUE):
  paid_row_value = 0
  for index, row in df.iterrows():
    # Check if the index before had was one of the paid rows
      if row[cols[DESCRIPT_COL]] == 'Got Payed':
        paid_row_value = row[cols[REMAINDER_COL]]
      else:
        df.at[index, cols[REMAINDER_COL]] = paid_row_value

  df[cols[REMAINDER_COL]] = df[cols[REMAINDER_COL]].fillna(0)




def clean_up_remainder_col(df):
  PR_INDEX = 0
  PR_VALUE = 1

  cols = {
    DESCRIPT_COL : 'Description',
    REMAINDER_COL : 'Remainder'
  }

  fill_for_remainder_rows(df, cols, PR_INDEX, PR_VALUE)

  for index, row in df.iterrows():
    if row[cols[DESCRIPT_COL]] == 'Got Payed':
      if index >= 5:
        df.at[index, cols[REMAINDER_COL]] += df.at[index - 1, cols[REMAINDER_COL]]


  return df



df = clean_up_remainder_col(df)

In [203]:
df.head(40)

,Date,Description,Category,Income,Subtract,Balance,Student Debt,Emergency Savings,Remainder
1,2024-03-01,Got Payed,Income,2000,0,2000,8250,0,0.0
2,2024-03-01,Church Giving,Church,0,200,1800,8250,0,0.0
3,2024-03-01,Student Loan Payment,Debt,0,600,1200,7650,0,0.0
4,2024-03-01,Daily Driving,Driving,0,400,800,7650,0,0.0
5,2024-03-01,Phone Bill,Phone,0,120,680,7650,0,0.0
6,2024-03-01,Emergency,Saving,0,360,320,7650,360,0.0
7,2024-03-01,Invest,Saving,0,20,300,7650,380,0.0
8,2024-03-01,Groceries,Groceries,0,40,260,7650,380,0.0
9,2024-03-01,Eating Out,Entertainment,0,80,180,7650,380,0.0
10,2024-03-01,Gym Membership,Entertainment,0,50,130,7650,380,0.0
11,2024-03-16,Got Payed,Income,2000,0,2130,7650,380,130.0
12,2024-03-16,Church Giving,Church,0,200,1930,7650,380,130.0
13,2024-03-16,Student Loan Payment,Debt,0,600,1330,7050,380,130.0
14,2024-03-16,Daily Driving,Driving,0,400,930,7050,380,130.0
15,2024-03-16,Phone Bill,Phone,0,120,810,7050,380,130.0
16,2024-03-16,Emergency,Saving,0,360,450,7050,740,130.0
17,2024-03-16,Invest,Saving,0,20,430,7050,760,130.0
18,2024-03-16,Groceries,Groceries,0,40,390,7050,760,130.0
19,2024-03-16,Eating Out,Entertainment,0,80,310,7050,760,130.0
20,2024-03-16,Gym Membership,Entertainment,0,50,260,7050,760,130.0
21,2024-03-31,Got Payed,Income,2000,0,2260,7050,760,390.0
22,2024-03-31,Church Giving,Church,0,200,2060,7050,760,260.0
23,2024-03-31,Student Loan Payment,Debt,0,600,1460,6450,760,260.0
24,2024-03-31,Daily Driving,Driving,0,400,1060,6450,760,260.0
25,2024-03-31,Phone Bill,Phone,0,120,940,6450,760,260.0
26,2024-03-31,Emergency,Saving,0,360,580,6450,1120,260.0
27,2024-03-31,Invest,Saving,0,20,560,6450,1140,260.0
28,2024-03-31,Groceries,Groceries,0,40,520,6450,1140,260.0
29,2024-03-31,Eating Out,Entertainment,0,80,440,6450,1140,260.0
30,2024-03-31,Gym Membership,Entertainment,0,50,390,6450,1140,260.0
31,2024-04-15,Got Payed,Income,2000,0,2390,6450,1140,650.0
32,2024-04-15,Church Giving,Church,0,200,2190,6450,1140,390.0
33,2024-04-15,Student Loan Payment,Debt,0,600,1590,5850,1140,390.0
34,2024-04-15,Daily Driving,Driving,0,400,1190,5850,1140,390.0
35,2024-04-15,Phone Bill,Phone,0,120,1070,5850,1140,390.0
36,2024-04-15,Emergency,Saving,0,360,710,5850,1500,390.0
37,2024-04-15,Invest,Saving,0,20,690,5850,1520,390.0
38,2024-04-15,Groceries,Groceries,0,40,650,5850,1520,390.0
39,2024-04-15,Eating Out,Entertainment,0,80,570,5850,1520,390.0
40,2024-04-15,Gym Membership,Entertainment,0,50,520,5850,1520,390.0